POST http://localhost:5000/api/v1/company
Content-Type: application/json

{
	"type": "needHelp",
	"name":"name",
	"address": "adress",
	"businessType": "businessType",
	"issues": "issues",
	"numberOfJobs": "numberOfJobs",
	"whatHappened": "whatHappened",
	"whatNeed": "whatNeed",
	"socialNetworks": "socialNetworks",
	"email": "email",
	"phone": "phone",
	"coords": {
		"lat": "15.12334234",
		"lng": "45.23454355"
		}
}

###

GET http://localhost:5000/api/v1/company/5ea58c8bded758d370ab3614
Accept: application/json

###
GET http://localhost:5000/api/v1/getAllMarkers

###
